return {
    direct_pokermon_edits = {},
    runtime_overrides = {
        source = "balance/elemental_pokemon_overrides.lua",
        wrapped_functions = { "calculate" },
        revert = "Set gameplay.enable_pokemon_overrides = false or disable per-Pokemon toggles in config.lua",
        pokemon = {
            { key = "j_poke_bulbasaur", name = "Bulbasaur", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Seed Recovery", "Growth" } },
            { key = "j_poke_ivysaur", name = "Ivysaur", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Overgrow", "Growth" } },
            { key = "j_poke_venusaur", name = "Venusaur", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Solar Bloom", "Growth" } },
            { key = "j_poke_charmander", name = "Charmander", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Kindling", "Blaze" } },
            { key = "j_poke_charmeleon", name = "Charmeleon", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Flare Temper", "Blaze" } },
            { key = "j_poke_charizard", name = "Charizard", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Inferno Engine", "Blaze" } },
            { key = "j_poke_squirtle", name = "Squirtle", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Shell Guard" } },
            { key = "j_poke_wartortle", name = "Wartortle", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Tidal Guard" } },
            { key = "j_poke_blastoise", name = "Blastoise", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Hydro Cannon" } },
            { key = "j_poke_pikachu", name = "Pikachu", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Static Spark", "Static" } },
            { key = "j_poke_raichu", name = "Raichu", source_file = "pokemon/pokejokers_01.lua", enabled = true, mechanics = { "Overcharge", "Static" } },
            { key = "j_poke_geodude", name = "Geodude", source_file = "pokemon/pokejokers_03.lua", enabled = true, mechanics = { "Rock Body" } },
            { key = "j_poke_onix", name = "Onix", source_file = "pokemon/pokejokers_04.lua", enabled = true, mechanics = { "Burrow", "Armor" } },
            { key = "j_poke_steelix", name = "Steelix", source_file = "pokemon/pokejokers_07.lua", enabled = true, mechanics = { "Iron Faultline", "Armor" } },
            { key = "j_poke_gyarados", name = "Gyarados", source_file = "pokemon/pokejokers_05.lua", enabled = true, mechanics = { "Rage Current", "Rage" } },
            { key = "j_poke_jolteon", name = "Jolteon", source_file = "pokemon/pokejokers_05.lua", enabled = true, mechanics = { "Volt Absorb", "Static" } },
            { key = "j_poke_zapdos", name = "Zapdos", source_file = "pokemon/pokejokers_05.lua", enabled = true, mechanics = { "Thunderstorm", "Static" } },
            { key = "j_poke_oddish", name = "Oddish", source_file = "pokemon/pokejokers_02.lua", enabled = true, mechanics = { "Sleep Powder" } },
            { key = "j_poke_snorlax", name = "Snorlax", source_file = "pokemon/pokejokers_05.lua", enabled = true, mechanics = { "Rest" } },
            { key = "j_poke_magikarp", name = "Magikarp", source_file = "pokemon/pokejokers_05.lua", enabled = true, mechanics = { "Splash Charge", "Splash" } },
        },
    },
}
