local ElementalEditions = assert(rawget(_G, "ElementalEditions"))

ElementalEditions.constants = {
    element_keys = { "fire", "water", "earth", "lightning", "grass" },
    elements = {
        fire = {
            key = "fire",
            label = "Fire",
            attack_type = "Fire",
            status = "burned",
            edition_key = "fire",
            types = { "Fire" },
        },
        water = {
            key = "water",
            label = "Water",
            attack_type = "Water",
            status = "confused",
            edition_key = "water",
            types = { "Water" },
        },
        earth = {
            key = "earth",
            label = "Earth",
            attack_type = "Earth",
            status = "dazed",
            edition_key = "earth",
            types = { "Earth", "Metal" },
        },
        lightning = {
            key = "lightning",
            label = "Lightning",
            attack_type = "Lightning",
            status = "paralyzed",
            edition_key = "lightning",
            types = { "Lightning" },
        },
        grass = {
            key = "grass",
            label = "Grass",
            attack_type = "Grass",
            status = "asleep",
            edition_key = nil,
            types = { "Grass" },
            enhancement = "m_poke_flower",
        },
    },
    type_aliases = {
        Electric = "Lightning",
        Ground = "Earth",
        Rock = "Earth",
        Steel = "Metal",
        Flying = "Bird",
        Normal = "Colorless",
    },
    hand_key_by_name = {
        ["High Card"] = "high_card",
        ["Pair"] = "pair",
        ["Two Pair"] = "two_pair",
        ["Three of a Kind"] = "three_of_a_kind",
        ["Straight"] = "straight",
        ["Flush"] = "flush",
        ["Full House"] = "full_house",
        ["Four of a Kind"] = "four_of_a_kind",
        ["Straight Flush"] = "straight_flush",
        ["Five of a Kind"] = "five_of_a_kind",
        ["Flush House"] = "flush_house",
        ["Flush Five"] = "flush_five",
    },
    scalable_result_fields = {
        "mult_mod",
        "chip_mod",
        "Xmult_mod",
        "x_mult_mod",
        "h_mult",
        "h_chips",
        "dollars",
        "money",
    },
    status_keys = {
        burned = true,
        paralyzed = true,
        dazed = true,
        confused = true,
        asleep = true,
    },
    status_to_element = {
        burned = "fire",
        paralyzed = "lightning",
        dazed = "earth",
        confused = "water",
        asleep = "grass",
    },
    tracked_counters = {
        blaze = true,
        static = true,
        growth = true,
        rage = true,
        splash = true,
        armor = true,
    },
}

return ElementalEditions.constants
