return {
    debug = {
        enabled = false,
        debug_enabled = false,
        file_enabled = false,
        debug_file_enabled = false,
        lovely_enabled = true,
        debug_lovely_enabled = true,
        scoring = true,
        debug_scoring = true,
        discard = true,
        debug_discard = true,
        damage = false,
        debug_damage = false,
        status = true,
        debug_status = true,
        editions = true,
        debug_editions = true,
        challenges = true,
        debug_challenges = true,
        messages = false,
        debug_messages = false,
        overrides = false,
        debug_overrides = false,
        performance = false,
        debug_performance = false,
        verbose = false,
        debug_verbose = false,
        trace_scoring_every_n = 1,
        debug_trace_scoring_every_n = 1,
        sample_rate = 1,
        debug_sample_rate = 1,
    },
    editions = {
        fire = true,
        water = true,
        earth = true,
        lightning = true,
        singed = true,
    },
    gameplay = {
        enable_pokemon_hp = true,
        enable_elemental_damage = true,
        enable_discard_damage = true,
        enable_joker_statuses = true,
        enable_status_edition_transforms = true,
        enable_status_edition_visuals = true,
        status_editions_visual_only = true,
        preserve_existing_joker_editions = true,
        status_visuals_overwrite_existing_editions = false,
        enable_boss_status_attacks = true,
        enable_run_start_elemental_cards = false,
        enable_held_card_pressure = false,
        enable_auto_revive_end_of_blind = true,
        allow_non_pokemon_hp = false,
        damage_targeting_mode = "all",
        enable_pokemon_overrides = true,
        enable_damage_messages = true,
        message_verbosity = "normal",
        enable_trainer_challenges = true,
        enable_boss_pokemon_effects = true,
        enable_card_creation_effects = true,
    },
    battle_mode = {
        starter_per_element = 1,
        growth_per_ante = 1,
        starter_deck_joker = "j_poke_bulbasaur",
        starter_deck_item = "c_poke_pokeball",
        challenge_starters = {
            "j_poke_bulbasaur",
            "j_poke_charmander",
            "j_poke_squirtle",
            "j_poke_pikachu",
        },
    },
    hp = {
        basic = 30,
        evolved = 45,
        rare = 60,
        legendary = 80,
        auto_revive_percent = 0.25,
        auto_revive_min = 1,
    },
    damage = {
        scored_damage_base = 6,
        discard_damage_base = 3,
        held_damage_base = 1,
        same_type_resist = 0.50,
        lightning_ground_multiplier = 0.25,
        earth_bird_multiplier = 0.25,
        min_multiplier = 0,
        max_multiplier = 4,
        super_effective_threshold = 1.5,
        resisted_threshold = 0.75,
        apply_to_knocked_out = false,
        debug_aoe_damage = false,
    },
    effectiveness = {
        fire = {
            Grass = 2,
            Ice = 2,
            Bug = 2,
            Metal = 2,
            Fire = 0.5,
            Water = 0.5,
            Earth = 0.5,
            Dragon = 0.5,
        },
        water = {
            Fire = 2,
            Earth = 2,
            Water = 0.5,
            Grass = 0.5,
            Dragon = 0.5,
        },
        lightning = {
            Water = 2,
            Bird = 2,
            Lightning = 0.5,
            Grass = 0.5,
            Dragon = 0.5,
            Earth = 0.25,
        },
        earth = {
            Fire = 2,
            Lightning = 2,
            Poison = 2,
            Metal = 2,
            Grass = 0.5,
            Bug = 0.5,
            Bird = 0.25,
        },
        grass = {
            Water = 2,
            Earth = 2,
            Fire = 0.5,
            Grass = 0.5,
            Poison = 0.5,
            Bird = 0.5,
            Bug = 0.5,
            Dragon = 0.5,
            Metal = 0.5,
        },
    },
    hand_scaling = {
        high_card = 1.0,
        pair = 1.0,
        two_pair = 1.25,
        three_of_a_kind = 1.25,
        straight = 1.5,
        flush = 1.5,
        full_house = 1.75,
        four_of_a_kind = 1.75,
        straight_flush = 2.0,
        five_of_a_kind = 2.0,
        flush_house = 2.0,
        flush_five = 2.0,
    },
    status = {
        chance_per_scored_card = 0.20,
        chance_per_discarded_card = 0.10,
        bonus_per_extra_channel = 0.05,
        super_effective_bonus = 0.10,
        resisted_penalty = 0.05,
        max_chance = 0.60,
        burned = {
            duration = 3,
            contribution_mult = 0.75,
            dot_damage = 2,
            fire_resist_mult = 0.50,
            blaze_mult_per_fire = 1,
        },
        paralyzed = {
            duration = 3,
            skip_chance = 0.25,
            static_per_lightning = 1,
            static_chip_per_counter = 5,
        },
        dazed = {
            duration = 1,
            contribution_mult = 0.50,
            incoming_mult = 0.50,
        },
        confused = {
            duration = 2,
            contribution_mult = 0.75,
            redirect_heal_chance = 0.25,
            water_heal = 2,
        },
        asleep = {
            duration = 1,
            end_hand_heal = 4,
            growth_on_wake = 1,
        },
    },
    pressure = {
        fire_mult = 4,
        fire_ramp_every = 3,
        water_starting_chips = 40,
        water_chip_loss = 5,
        water_minimum_chips = 10,
        lightning_chip_per_card = 10,
        earth_base_chips = 20,
        earth_repeat_bonus = 5,
        earth_durable_bonus = 5,
    },
    card_status = {
        singed_chip_loss = 5,
        fire_singed_chance = 0.20,
    },
    messages = {
        message_duration_multiplier = 1.45,
        damage_message_duration = 0.80,
        status_message_duration = 1.05,
        summary_message_duration = 1.35,
        aoe_summary_threshold = 2,
        show_individual_damage_up_to = 2,
        show_effectiveness_summary = true,
        aggregate_aoe_damage_messages = true,
        max_messages_per_scoring_event = 4,
        flavor = {
            fire = { "Scorched!", "Burn hit!", "Superheated!" },
            water = { "Splash damage!", "Washed out!", "The current surges!" },
            lightning = { "Shocked!", "Static burst!", "Voltage spike!" },
            earth = { "Rocked!", "Quake hit!", "Grounded!" },
            grass = { "Vines lash out!", "Sleep spores!", "Bloom burst!" },
        },
    },
    performance = {
        logging_enabled = false,
        performance_logging_enabled = false,
        log_threshold_ms = 4,
        performance_log_threshold_ms = 4,
    },
    trainer_challenges = {
        enabled = true,
        youngster_first_battle = true,
        brocks_rock_wall = true,
        mistys_tidal_trial = true,
        surge_voltage_test = true,
        erikas_bloom_garden = true,
    },
    boss = {
        element_damage_bonus = 2,
        status_bonus = 0.10,
        after_hand_transform_chance = 0.50,
        after_discard_transform_chance = 0.35,
    },
    card_creation = {
        enabled = true,
        max_created_per_hand = 1,
        max_created_per_blind = 3,
        transform_instead_of_create = true,
    },
    overrides = {
        enabled = true,
        debug_logging = false,
        pokemon = {
            bulbasaur = true,
            ivysaur = true,
            venusaur = true,
            charmander = true,
            charmeleon = true,
            charizard = true,
            squirtle = true,
            wartortle = true,
            blastoise = true,
            pikachu = true,
            raichu = true,
            geodude = true,
            onix = true,
            steelix = true,
            gyarados = true,
            jolteon = true,
            zapdos = true,
            oddish = true,
            snorlax = true,
            magikarp = true,
            caterpie = true,
            pidgey = true,
            sandshrew = true,
            psyduck = true,
            golduck = true,
            staryu = true,
            starmie = true,
            voltorb = true,
            electrode = true,
            eevee = true,
            vaporeon = true,
            flareon = true,
            butterfree = true,
            sandslash = true,
            vileplume = true,
            bellossom = true,
            growlithe = true,
            arcanine = true,
            dragonite = true,
        },
    },
    shop = {
        in_shop = true,
        weight = 7,
        extra_cost = 4,
    },
    starter = {
        infuse_existing_cards = true,
        cards_per_element = 1,
    },
    dev = {
        debug_logging = false,
        discovered = true,
        unlocked = true,
    },
}
