return {
    descriptions = {
        Back = {
            b_elem_battledeck = {
                name = "Elemental Battle Deck",
                text = {
                    "Start with {C:attention,T:j_poke_bulbasaur}#1#{}",
                    "and a {C:item,T:c_poke_pokeball}#2#{}",
                    "Seed one {C:red}Fire{}, {C:blue}Water{}, {C:attention}Earth{},",
                    "and {C:yellow}Lightning{} card at run start",
                    "Gain {C:attention}#3#{} more of each every Ante",
                },
            },
        },
        Edition = {
            e_elem_fire = {
                name = "Fire",
                text = {
                    "Adds {C:mult}+#1#{} Mult",
                    "when this card scores",
                    "Uses this run: {C:attention}#2#{}",
                    "Scored hits deal {C:red}Fire{} damage to all Pokemon Jokers",
                    "May inflict {C:red}Burned{} and respects type effectiveness",
                    "Fire Pokemon often resist or exploit Fire pressure",
                },
            },
            e_elem_water = {
                name = "Water",
                text = {
                    "Starts at {C:chips}+#1#{} chips",
                    "loses {C:chips}#2#{} after scoring",
                    "Current value: {C:chips}+#3#{}",
                    "Scored hits deal {C:blue}Water{} damage to all Pokemon Jokers",
                    "May inflict {C:blue}Confused{} and respects type effectiveness",
                    "Water pressure can cleanse Burn and power Water synergies",
                },
            },
            e_elem_lightning = {
                name = "Lightning",
                text = {
                    "Adds {C:chips}+#1#{} chips",
                    "per scored {C:attention}Lightning{} card",
                    "Scored hits deal {C:attention}Lightning{} damage to all Pokemon Jokers",
                    "May inflict {C:yellow}Paralyzed{} and respects type effectiveness",
                    "Electric Pokemon can store and release Static charge",
                },
            },
            e_elem_earth = {
                name = "Earth",
                text = {
                    "Adds {C:chips}+#1#{} chips",
                    "{C:chips}+#2#{} per repeated rank",
                    "{C:chips}+#3#{} per Stone, Steel, or Gold card",
                    "Scored hits deal {C:attention}Earth{} damage to all Pokemon Jokers",
                    "May inflict {C:attention}Dazed{} and respects type effectiveness",
                    "Earth can ground Lightning and empower sturdy Pokemon",
                },
            },
            e_elem_singed = {
                name = "Singed",
                text = {
                    "Loses {C:chips}#1#{} more chips",
                    "each time this card scores",
                    "Current penalty: {C:chips}-#2#{}",
                },
            },
        },
    },
    misc = {
        dictionary = {
            elem_fire = "Fire",
            elem_water = "Water",
            elem_earth = "Earth",
            elem_lightning = "Lightning",
            elem_grass = "Grass",
            elem_singed = "Singed",
            elem_hp = "HP",
            elem_hp_tooltip = "HP: Elemental cards can damage Pokemon Jokers. At 0 HP, a Pokemon is Knocked Out until it recovers.",
            elem_elemental_damage = "Elemental Damage",
            elem_elemental_damage_tooltip = "Elemental Damage: Scored elemental cards damage Pokemon Jokers. Discarded elemental cards may apply weaker pressure.",
            elem_type_effectiveness = "Type Effectiveness",
            elem_type_effectiveness_tooltip = "Type Effectiveness: Super effective hits deal more HP damage. Resisted hits deal less. Matching types usually resist their own element.",
            elem_knocked_out = "Knocked Out",
            elem_knocked_out_tooltip = "Knocked Out: This Pokemon has 0 HP. It cannot use Elemental Editions battle effects until revived or recovered.",
            elem_revived = "Revived",
            elem_cleansed = "Cleansed",
            elem_recovered = "Recovered",
            elem_woke_up = "Woke Up",
            elem_requires_pokermon = "Pokermon required",
            elem_super_effective = "Super effective!",
            elem_resisted = "Resisted!",
            elem_no_effect = "No effect!",
            elem_override_heading = "Elemental",
            elem_override_mechanics = "Mechanics",
            elem_flower_channel_heading = "Flower Cards",
            elem_flower_channel_desc_1 = "Count as Grass battle cards for Elemental Editions.",
            elem_flower_channel_desc_2 = "They may cause Sleep, healing, Growth, and Grass-type synergies.",
            elem_status_burned = "Burned",
            elem_status_paralyzed = "Paralyzed",
            elem_status_dazed = "Dazed",
            elem_status_confused = "Confused",
            elem_status_asleep = "Asleep",
            elem_status_burned_desc_1 = "Fire status. Takes damage over time and may weaken supported effects.",
            elem_status_burned_desc_2 = "Fire cards can fuel Blaze bonuses. Water effects can cleanse it. Uses Fire visuals when safe.",
            elem_status_paralyzed_desc_1 = "Lightning status. May prevent supported actions, but Lightning pressure builds Static charge.",
            elem_status_paralyzed_desc_2 = "Earth effects may ground it. Uses Lightning visuals when safe.",
            elem_status_dazed_desc_1 = "Earth status. The next supported effect is weakened, but incoming damage is reduced first.",
            elem_status_dazed_desc_2 = "Clears quickly after bracing. Uses Earth visuals when safe.",
            elem_status_confused_desc_1 = "Water status. Supported effects are less reliable, but Water pressure may heal or redirect damage.",
            elem_status_confused_desc_2 = "Water effects can also cleanse it. Uses Water visuals when safe.",
            elem_status_asleep_desc_1 = "Grass status. This Pokemon may skip its next supported action, but heals or grows while resting.",
            elem_status_asleep_desc_2 = "Fire pressure may wake it early. Uses Grass status identity when safe.",
            elem_counter_blaze = "Blaze",
            elem_counter_static = "Static",
            elem_counter_growth = "Growth",
            elem_counter_rage = "Rage",
            elem_counter_splash = "Splash",
            elem_counter_armor = "Armor",
        },
        labels = {
            elem_fire = "Fire",
            elem_water = "Water",
            elem_earth = "Earth",
            elem_lightning = "Lightning",
            elem_grass = "Grass",
            elem_singed = "Singed",
        },
        challenge_names = {
            c_elem_youngster_first_battle = "Youngster's First Battle",
            c_elem_brocks_rock_wall = "Brock's Rock Wall",
            c_elem_mistys_tidal_trial = "Misty's Tidal Trial",
            c_elem_surge_voltage_test = "Lt. Surge's Voltage Test",
            c_elem_erikas_bloom_garden = "Erika's Bloom Garden",
        },
    },
}
